apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
