---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  storageClassName: local-path

