apiVersion: v1
kind: ConfigMap
metadata:
  name: sponsorblock-config
data:
  config.json: |
    {
      "apikey": "",

      "devices": [
        { "name": "YouTube on TV", "screen_id": "pk847bpdt1lb2smuohe401ms40" },
        { "name": "YouTube on TV", "screen_id": "mau2g7ggspcs86a724ump6siu" }
      ],

      "skip_count_tracking": true,
      "mute_ads": false,
      "skip_ads": false,
      "auto_play": true,

      "channel_whitelist": [],
      "skip_categories": [
        "sponsor",
        "selfpromo",
        "exclusive_access",
        "intro",
        "outro"
      ]
    }     
