apiVersion: apps/v1
kind: Deployment
metadata:
  name: sponsorblock
  labels:
    app: sponsorblock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sponsorblock
  template:
    metadata:
      labels:
        app: sponsorblock
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: sponsorblock
          image: dmunozv04/isponsorblocktv:v2.5.3
          volumeMounts:
            - name: config-volume
              mountPath: /app/data/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: sponsorblock-config
