#!/usr/bin/env sh

# FIX: ignoring untrusted substituter you are not a trusted user.

FLAKE=${FLAKE:-.}
KERNEL=$(uname -s)
OUTPUT="$FLAKE#$1"
FEATURES="nix-command flakes pipe-operators"

if test "$KERNEL" = "Linux"; then
  sudo NIX_CONFIG="extra-experimental-features = $FEATURES" nixos-rebuild switch --flake "$OUTPUT"
elif test "$KERNEL" = "Darwin"; then
  sudo NIX_CONFIG="extra-experimental-features = $FEATURES" nix \
       run nix-darwin -- switch --flake "$OUTPUT"
fi
