apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
data:
  qBittorrent.conf: |
    [BitTorrent]
    Session\AddTorrentStopped=false
    Session\DefaultSavePath=/downloads
    Session\DisableAutoTMMByDefault=false
    Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
    Session\Interface=wg0
    Session\InterfaceName=wg0
    Session\Port=8419
    Session\QueueingSystemEnabled=true
    Session\SSL\Port=29697
    Session\ShareLimitAction=Stop

    [Core]
    AutoDeleteAddedTorrentFile=Never

    [Meta]
    MigrationVersion=8

    [Network]
    Proxy\HostnameLookupEnabled=false
    Proxy\Profiles\BitTorrent=true
    Proxy\Profiles\Misc=true
    Proxy\Profiles\RSS=true

    [Preferences]
    General\Locale=en
    WebUI\CustomHTTPHeaders="content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline' develop.theme-park.dev raw.githubusercontent.com use.fontawesome.com; img-src 'self' themepark.homelab.lan raw.githubusercontent.com data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self'; font-src use.fontawesome.com;"
    WebUI\CustomHTTPHeadersEnabled=true
    WebUI\LocalHostAuth=false
    WebUI\Password_PBKDF2="@ByteArray(V5kcWZHn4FTxBM8IxsnsCA==:HPbgopaa1ZO199s4zmJAZfJ+gmGKUyAQMX1MjbphhHTtup80tt/FOFshUMRQnvCqAxAu31F6ziiUqpuUQCytPg==)"
    WebUI\Port=8280
